import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'uz' | 'ru' | 'en';

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Lang, string>> = {
  // ── SIDEBAR ──
  'nav.haqida': { uz: "Dastur haqida", ru: 'О программе', en: 'About App' },
  'nav.kurslar': { uz: 'Kurslar', ru: 'Курсы', en: 'Courses' },
  'nav.oqmatlar': { uz: "O'quv materiallari", ru: 'Учебные материалы', en: 'Study Materials' },
  'nav.savol_javob': { uz: 'Savol–javoblar', ru: 'Вопросы–Ответы', en: 'Q&A' },
  'nav.reyting': { uz: 'Reyting', ru: 'Рейтинг', en: 'Rating' },
  'nav.mavjud_testlar': { uz: 'Mavjud testlar', ru: 'Доступные тесты', en: 'Available Tests' },
  'nav.mavjud_kazuslar': { uz: 'Mavjud kazuslar', ru: 'Доступные казусы', en: 'Available Cases' },
  'nav.bilim_olish': { uz: 'Sinovni boshlash', ru: 'Начать тестирование', en: 'Start Exam' },
  'nav.sinov': { uz: 'Sinovni boshlash', ru: 'Начать тестирование', en: 'Start Exam' },
  'nav.natijalar': { uz: 'Reyting', ru: 'Рейтинг', en: 'Rating' },
  'nav.kazus_yaratish': { uz: 'Kazus yaratish', ru: 'Создать казус', en: 'Create Case' },
  'nav.ustoz': { uz: 'Ustoz kabineti', ru: 'Кабинет учителя', en: 'Teacher Panel' },
  'nav.testlar': { uz: 'Testlar kabineti', ru: 'Кабинет тестов', en: 'Test Cabinet' },
  'nav.royhat': { uz: "Ro'yhat", ru: 'Список', en: 'List' },
  'nav.oquvchilar': { uz: "O'quvchilarim", ru: 'Мои учащиеся', en: 'My Students' },
  'nav.bot_yangilik': { uz: 'Bot Yangiligi', ru: 'Бот Новости', en: 'Bot News' },
  'nav.profil': { uz: 'Profil', ru: 'Профиль', en: 'Profile' },
  'nav.admin': { uz: 'Admin Panel', ru: 'Панель Admin', en: 'Admin Panel' },
  'nav.yordam': { uz: 'Yordam', ru: 'Помощь', en: 'Help' },
  'nav.smart_talim': { uz: "Smart ta'lim", ru: 'Smart обучение', en: 'Smart learning' },

  // ── HEADER ──
  'header.title': { uz: 'JurisMind', ru: 'JurisMind', en: 'JurisMind' },
  'header.subtitle': { uz: "Bilimingizni sun'iy intellekt bilan yuksaltiring", ru: 'Развивайте знания с ИИ', en: 'Elevate your knowledge with AI' },
  'header.login': { uz: 'Kirish', ru: 'Войти', en: 'Login' },
  'header.logout': { uz: 'Chiqish', ru: 'Выйти', en: 'Logout' },
  'header.my_profile': { uz: 'Mening profilim', ru: 'Мой профиль', en: 'My profile' },

  // ── PAGE TITLES ──
  'page.sinov': { uz: 'Sinovni boshlash', ru: 'Начать тестирование', en: 'Start Exam' },
  'page.natijalar': { uz: 'Natijalar tahlili', ru: 'Анализ результатов', en: 'Results Analysis' },
  'page.testlar': { uz: 'Mavjud testlar', ru: 'Доступные тесты', en: 'Available Tests' },
  'page.kazuslar': { uz: 'Mavjud kazuslar', ru: 'Доступные казусы', en: 'Available Cases' },
  'page.oqmatlar': { uz: "O'quv materiallari", ru: 'Учебные материалы', en: 'Study Materials' },
  'page.profil': { uz: 'Mening profilim', ru: 'Мой профиль', en: 'My Profile' },
  'page.savol_javob': { uz: 'Savol va Javoblar', ru: 'Вопросы и Ответы', en: 'Questions & Answers' },
  'page.haqida': { uz: 'Dastur haqida', ru: 'О программе', en: 'About' },

  // ── SINOV BOSHLASH ──
  'sinov.badge': { uz: 'FanFaster Platformasi', ru: 'Платформа FanFaster', en: 'FanFaster Platform' },
  'sinov.title1': { uz: 'Kelajak mutaxassislari', ru: 'Будущим специалистам', en: 'For future specialists' },
  'sinov.title2': { uz: 'uchun maxsus', ru: 'специальная', en: 'specially designed' },
  'sinov.title3': { uz: 'tizim', ru: 'система', en: 'system' },
  'sinov.desc': { uz: "FanFaster orqali o'z bilimingizni barcha fanlardan AI yordamida professional darajada sinab ko'ring.", ru: 'Проверьте свои знания по всем предметам на профессиональном уровне с помощью ИИ через FanFaster.', en: 'Test your knowledge in all subjects at a professional level with AI through FanFaster.' },
  'sinov.start_btn': { uz: "Bilim olishni boshlash", ru: 'Начать обучение', en: 'Start Learning' },
  'sinov.kod_title': { uz: 'Sinov Kodini Kiriting', ru: 'Введите Код Теста', en: 'Enter Exam Code' },
  'sinov.kod_desc': { uz: 'Test yoki kazusni boshlash uchun 5 xonali maxfiy kodni kiriting.', ru: 'Введите 5-значный секретный код для начала теста или казуса.', en: 'Enter the 5-digit code to start the test or case.' },
  'sinov.start': { uz: 'SINOVNI BOSHLASH', ru: 'НАЧАТЬ ТЕСТ', en: 'START EXAM' },
  'sinov.home': { uz: 'Bosh sahifaga qaytish', ru: 'На главную страницу', en: 'Back to home' },
  'sinov.waiting_title': { uz: 'Ustoz kutilmoqda...', ru: 'Ожидание учителя...', en: 'Waiting for teacher...' },
  'sinov.waiting_name': { uz: 'Sinov nomi:', ru: 'Название теста:', en: 'Exam name:' },
  'sinov.waiting_code': { uz: 'Kodingiz:', ru: 'Ваш код:', en: 'Your code:' },
  'sinov.cancel': { uz: 'Bekor qilish', ru: 'Отмена', en: 'Cancel' },

  // ── SAYT HAQIDA ──
  'about.scroll_down': { uz: 'Pastga aylantiring', ru: 'Прокрутите вниз', en: 'Scroll down' },
  'about.hero_badge': { uz: "Kelajakni shu yerdan boshlang", ru: 'Начните будущее здесь', en: 'Start your future here' },
  'about.hero_title1': { uz: 'Fan', ru: 'Fan', en: 'Fan' },
  'about.hero_title2': { uz: 'intellektual ta\'lim platformasi', ru: 'интеллектуальная платформа', en: 'an intellectual learning platform' },
  'about.hero_desc': { uz: "FanFaster — oddiy platforma emas. Bu sun'iy intellekt va inson tafakkurining strategik sintezi. Biz bilim berish bilan cheklanmaymiz, biz sizni raqobatdan bir qadam oldinda yuradigan professionalga aylantiramiz.", ru: 'FanFaster — это не просто платформа. Это стратегический синтез ИИ и человеческого интеллекта. Мы превращаем вас в профессионала, который на шаг впереди.', en: 'FanFaster is not just a platform. It is a strategic synthesis of AI and human intellect. We turn you into a professional who stays one step ahead.' },
  'about.features_section': { uz: 'Funksiyalar', ru: 'Функции', en: 'Features' },
  'about.oqmat_title': { uz: "O'quv materiallari", ru: 'Учебные материалы', en: 'Study Materials' },
  'about.oqmat_desc': { uz: "Axborot shovqinidan xalos bo'ling. Bizda faqat eng sara, tizimlashtirilgan va multimedial kontent mavjud. Bu shunchaki o'qish emas, bu bilimni ong ostiga muhrlash san'atidir.", ru: 'Избавьтесь от информационного шума. У нас только лучший, систематизированный и мультимедийный контент.', en: 'Get rid of information noise. We have only the best, structured and multimedia content.' },
  'about.oqmat_btn': { uz: 'Bilim olishni boshlash', ru: 'Начать обучение', en: 'Start Learning' },
  'about.sj_title': { uz: 'Savol–Javoblar', ru: 'Вопросы–Ответы', en: 'Q&A' },
  'about.sj_desc': { uz: "Reaksiyangizni professional darajaga ko'taring. Intellektual duellar maydoni sizni kutilmagan savollarga tayyorlaydi.", ru: 'Поднимите реакцию до профессионального уровня. Поле интеллектуальных дуэлей готовит вас к неожиданным вопросам.', en: 'Elevate your reactions to a professional level. The field of intellectual duels prepares you for unexpected questions.' },
  'about.sj_btn': { uz: 'Intellektni charxlash', ru: 'Развивать интеллект', en: 'Sharpen Your Mind' },
  'about.testlar_title': { uz: 'Mavjud testlar', ru: 'Доступные тесты', en: 'Available Tests' },
  'about.testlar_desc': { uz: "Statistika yolg'on gapirmaydi. O'z bilimingizni qat'iy va xolis filtrdan o'tkazing.", ru: 'Статистика не лжёт. Пропустите свои знания через строгий и объективный фильтр.', en: "Statistics don't lie. Put your knowledge through a strict and objective filter." },
  'about.testlar_btn': { uz: "O'z kuchingni sinab ko'r", ru: 'Проверь свои силы', en: 'Test Your Strength' },
  'about.kazuslar_title': { uz: 'Mavjud kazuslar', ru: 'Доступные казусы', en: 'Available Cases' },
  'about.kazuslar_desc': { uz: "Ekspertiza cho'qqisi. Haqiqiy muammolar, murakkab ssenariylar va sun'iy intellektning xolis bahosi.", ru: 'Вершина экспертизы. Реальные проблемы, сложные сценарии и объективная оценка ИИ.', en: 'The pinnacle of expertise. Real problems, complex scenarios and unbiased AI evaluation.' },
  'about.kazuslar_btn': { uz: 'Analitik tahlilga kirish', ru: 'Войти в аналитику', en: 'Enter Analytics' },
  'about.authors_title': { uz: 'Sayt mualliflari', ru: 'Авторы сайта', en: 'Site Authors' },
  'about.author1_role': { uz: "G'oya muallifi", ru: 'Автор идеи', en: 'Idea Author' },
  'about.author1_name': { uz: 'Azizov Nasimbek Abdumuxtorovich', ru: 'Азизов Насимбек Абдумухторович', en: 'Azizov Nasimbek Abdumuxtorovich' },
  'about.author1_desc': { uz: "Startap g'oya va loyiha muallifi, mentor, yuridik fanlar bo'yicha falsafa doktori (PhD), dotsent", ru: 'Автор стартап-идеи и проекта, ментор, PhD юридических наук, доцент', en: 'Startup idea and project author, mentor, PhD in Law, Associate Professor' },
  'about.author2_role': { uz: "G'oya muallifi", ru: 'Автор идеи', en: 'Idea Author' },
  'about.author2_name': { uz: "Abdurashidov Sherzodbek Abduvaxid o'g'li", ru: "Абдурашидов Шерзодбек Абдувахид ўғли", en: 'Abdurashidov Sherzodbek' },
  'about.author2_desc': { uz: "Startap g'oya va loyiha muallifi, dastur muhandisi", ru: 'Автор стартап-идеи и проекта, программный инженер', en: 'Startup idea and project author, software engineer' },
  'about.value_label': { uz: 'Bizning Qadriyatimiz', ru: 'Наша Ценность', en: 'Our Value' },
  'about.value_title': { uz: "FanFaster — bilimlar ummoni", ru: 'FanFaster — океан знаний', en: 'FanFaster — an ocean of knowledge' },
  'about.value_desc': { uz: "Audio, video, matn va kazuslar hamda savol javoblar uyg'unligi. Bu yerda har bir kazusni odil texnologiya baholaydi, har bir test esa sizni yangi ko'nikmalar sari yetaklaydi.", ru: 'Гармония аудио, видео, текста, казусов и вопросов-ответов. Здесь каждый казус оценивает справедливая технология, а каждый тест ведёт к новым навыкам.', en: 'A harmony of audio, video, text, cases and Q&A. Here every case is evaluated by fair technology, and every test guides you to new skills.' },
  'about.join_btn': { uz: "Bizga qo'shiling", ru: 'Присоединиться', en: 'Join Us' },

  // ── MAVJUD TESTLAR ──
  'tests.title': { uz: 'Mavjud Testlar', ru: 'Доступные тесты', en: 'Available Tests' },
  'tests.subtitle': { uz: "Bilimingizni sinash uchun ommaviy testlar ro'yxati", ru: 'Список публичных тестов для проверки знаний', en: 'List of public tests to check your knowledge' },
  'tests.search': { uz: 'Test nomi yoki kod orqali qidirish...', ru: 'Поиск по названию или коду теста...', en: 'Search by test name or code...' },
  'tests.empty': { uz: 'Hozircha mavjud test yo\'q', ru: 'Пока тестов нет', en: 'No tests available yet' },
  'tests.active': { uz: '● Faol', ru: '● Активен', en: '● Active' },
  'tests.waiting': { uz: '● Kutilmoqda', ru: '● Ожидает', en: '● Pending' },
  'tests.start': { uz: 'Boshlash', ru: 'Начать', en: 'Start' },
  'tests.views': { uz: 'ko\'rish', ru: 'просмотров', en: 'views' },
  'tests.questions': { uz: 'savol', ru: 'вопросов', en: 'questions' },
  'tests.min': { uz: 'min', ru: 'мин', en: 'min' },
  'tests.not_active_msg': { uz: 'Bu test hali ustoz tomonidan faollashtirilmagan', ru: 'Этот тест ещё не активирован преподавателем', en: 'This test has not been activated by the teacher yet' },
  'tests.login_required': { uz: 'Kirish talab etiladi', ru: 'Требуется вход', en: 'Login required' },
  'tests.login_required_msg': { uz: 'Testni boshlash uchun avval tizimga kiring', ru: 'Войдите в систему, чтобы начать тест', en: 'Please log in to start the test' },

  // ── MAVJUD KAZUSLAR ──
  'cases.title': { uz: 'Mavjud Kazuslar', ru: 'Доступные казусы', en: 'Available Cases' },
  'cases.subtitle': { uz: "Huquqiy vaziyatlarni tahlil qilish uchun ommaviy to'plamlar", ru: 'Публичные наборы для анализа правовых ситуаций', en: 'Public collections for analyzing legal situations' },
  'cases.search': { uz: 'Mavzu yoki kod bo\'yicha qidirish...', ru: 'Поиск по теме или коду...', en: 'Search by topic or code...' },
  'cases.empty': { uz: 'Hozircha mavjud kazus yo\'q', ru: 'Пока казусов нет', en: 'No cases available yet' },
  'cases.start': { uz: 'Boshlash', ru: 'Начать', en: 'Start' },
  'cases.untitled': { uz: 'Mavzusiz kazus', ru: 'Казус без темы', en: 'Untitled case' },
  'cases.not_active_msg': { uz: "Bu to'plam hali ustoz tomonidan faollashtirilmagan", ru: 'Этот набор ещё не активирован преподавателем', en: 'This collection has not been activated by the teacher yet' },

  // ── O'QUV MATERIALLAR (o'quvchi) ──
  'om.title': { uz: "O'quv Materiallari", ru: 'Учебные материалы', en: 'Study Materials' },
  'om.library': { uz: 'Kutubxona', ru: 'Библиотека', en: 'Library' },
  'om.search': { uz: 'Mavzulardan qidiring...', ru: 'Поиск по темам...', en: 'Search topics...' },
  'om.back': { uz: 'Orqaga', ru: 'Назад', en: 'Back' },
  'om.bobs': { uz: 'bob', ru: 'гл.', en: 'ch.' },
  'om.files': { uz: 'fayl', ru: 'файл', en: 'file' },
  'om.views': { uz: "ko'rish", ru: 'просм.', en: 'views' },
  'om.login_required': { uz: 'Tizimga kiring', ru: 'Войдите в систему', en: 'Log in' },
  'om.verified': { uz: 'Tasdiqlangan', ru: 'Подтверждено', en: 'Verified' },
  'om.secure_library': { uz: 'FanFaster Secure Library', ru: 'FanFaster Secure Library', en: 'FanFaster Secure Library' },

  // ── SAVOL-JAVOB (o'quvchi) ──
  'sj.title': { uz: 'Savol-Javoblar', ru: 'Вопросы-Ответы', en: 'Q&A' },
  'sj.library': { uz: 'Kutubxona', ru: 'Библиотека', en: 'Library' },
  'sj.back': { uz: 'ORQAGA', ru: 'НАЗАД', en: 'BACK' },
  'sj.bobs': { uz: 'bob', ru: 'гл.', en: 'ch.' },
  'sj.questions': { uz: 'savol', ru: 'вопросов', en: 'questions' },
  'sj.show_answer': { uz: "Javobni ko'rish", ru: 'Показать ответ', en: 'Show Answer' },
  'sj.knew': { uz: 'Bildim', ru: 'Знаю', en: 'Knew it' },
  'sj.didnt_know': { uz: 'Bilmadim', ru: 'Не знаю', en: "Didn't know" },
  'sj.back_to_question': { uz: '← Savolga qaytish', ru: '← К вопросу', en: '← Back to question' },
  'sj.all_answers': { uz: 'Barchasi', ru: 'Все', en: 'All' },
  'sj.all_answers_title': { uz: 'ta savol', ru: 'вопр.', en: 'ques.' },
  'sj.back_to_cards': { uz: 'Kartochkalarga qaytish', ru: 'К карточкам', en: 'Back to cards' },
  'sj.answer_label': { uz: '✅ Javob', ru: '✅ Ответ', ru2: '✅ Answer', en: '✅ Answer' },
  'sj.source': { uz: 'Manba: Lex.uz', ru: 'Источник: Lex.uz', en: 'Source: Lex.uz' },
  'sj.result_title': { uz: 'Natija', ru: 'Результат', en: 'Result' },
  'sj.knew_label': { uz: 'Bildim', ru: 'Знаю', en: 'Knew' },
  'sj.didnt_know_label': { uz: 'Bilmadim', ru: 'Не знаю', en: "Didn't Know" },
  'sj.back_to_bobs': { uz: 'BOBLARGA QAYTISH', ru: 'К ГЛАВАМ', en: 'BACK TO CHAPTERS' },
  'sj.restart': { uz: 'QAYTADAN BOSHLASH', ru: 'НАЧАТЬ ЗАНОВО', en: 'RESTART' },
  'sj.questions_nav': { uz: 'Savollar', ru: 'Вопросы', en: 'Questions' },
  'sj.knew_nav': { uz: 'Bildim', ru: 'Знаю', en: 'Knew' },
  'sj.didnt_know_nav': { uz: 'Bilmadim', ru: 'Не знаю', en: "Didn't Know" },
  'sj.question_num': { uz: 'Savol', ru: 'Вопрос', en: 'Question' },
  'sj.confirmed_answer': { uz: 'Tasdiqlangan javob', ru: 'Подтверждённый ответ', en: 'Confirmed answer' },

  // ── LOGIN MODAL ──
  'login.student': { uz: "O'quvchi", ru: 'Учащийся', en: 'Student' },
  'login.teacher': { uz: 'Ustoz', ru: 'Преподаватель', en: 'Teacher' },
  'login.sign_in': { uz: 'Kirish', ru: 'Войти', en: 'Sign In' },
  'login.register': { uz: "Ro'yxat", ru: 'Регистрация', en: 'Register' },
  'login.face_id': { uz: 'Face ID kirish', ru: 'Вход Face ID', en: 'Face ID Login' },
  'login.enter_account': { uz: 'Akkauntingizga kiring', ru: 'Войдите в аккаунт', en: 'Sign in to your account' },
  'login.new_account': { uz: 'Yangi akkount', ru: 'Новый аккаунт', en: 'New account' },
  'login.login_id': { uz: 'Login ID', ru: 'Логин ID', en: 'Login ID' },
  'login.password': { uz: 'Parol', ru: 'Пароль', en: 'Password' },
  'login.enter_btn': { uz: 'Kirish', ru: 'Войти', en: 'Sign In' },
  'login.no_account': { uz: "Akkauntingiz yo'qmi?", ru: 'Нет аккаунта?', en: "Don't have an account?" },
  'login.register_link': { uz: "Ro'yxatdan o'ting", ru: 'Зарегистрируйтесь', en: 'Register' },
  'login.first_name': { uz: 'Ism', ru: 'Имя', en: 'First Name' },
  'login.last_name': { uz: 'Familiya', ru: 'Фамилия', en: 'Last Name' },
  'login.login_field': { uz: 'Login', ru: 'Логин', en: 'Login' },
  'login.password_repeat': { uz: 'Parolni takrorlang', ru: 'Повторите пароль', en: 'Repeat password' },
  'login.register_btn': { uz: "Ro'yxatdan o'tish", ru: 'Зарегистрироваться', en: 'Register' },
  'login.have_account': { uz: 'Akkountingiz bormi?', ru: 'Есть аккаунт?', en: 'Have an account?' },
  'login.sign_in_link': { uz: 'Kirish', ru: 'Войти', en: 'Sign in' },
  'login.loading': { uz: 'Yuklanmoqda...', ru: 'Загрузка...', en: 'Loading...' },
  'login.face_enter': { uz: 'Face ID bilan kiring', ru: 'Войти с Face ID', en: 'Login with Face ID' },
  'login.face_camera': { uz: "Yuzingizni kameraga ko'rsating", ru: 'Покажите лицо в камеру', en: 'Show your face to the camera' },
  'login.face_register': { uz: "Face ID bilan ro'yxatdan o'tish", ru: "Регистрация с Face ID", en: 'Register with Face ID' },
  'login.face_register_desc': { uz: "Ism va familiyangizni kiriting, keyin yuzingizni skanerlang. Admin tasdiqini kuting.", ru: "Введите имя и фамилию, затем отсканируйте лицо. Ожидайте подтверждения администратора.", en: "Enter your name and surname, then scan your face. Wait for admin approval." },
  'login.face_warning': { uz: "Kirish uchun Face ID bilan ro'yxatdan o'tgan va admin tomonidan tasdiqlangan bo'lishingiz kerak.", ru: "Для входа нужно быть зарегистрированным с Face ID и подтверждённым администратором.", en: "To log in, you must be registered with Face ID and approved by an admin." },
  'login.back': { uz: 'Orqaga', ru: 'Назад', en: 'Back' },
  'login.forgot_pwd': { uz: 'Parolni unutdingizmi?', ru: 'Забыли пароль?', en: 'Forgot password?' },
  'login.pwd_min': { uz: 'Kamida 8 ta belgi', ru: 'Минимум 8 символов', en: 'Minimum 8 characters' },
  'login.pwd_upper': { uz: 'Kamida 1 katta harf (A-Z)', ru: 'Минимум 1 заглавная буква (A-Z)', en: 'Minimum 1 uppercase letter (A-Z)' },
  'login.pwd_num': { uz: 'Kamida 1 raqam (0-9)', ru: 'Минимум 1 цифра (0-9)', en: 'Minimum 1 number (0-9)' },
  'login.pwd_match': { uz: 'Parollar mos keldi', ru: 'Пароли совпадают', en: 'Passwords match' },
  'login.pwd_no_match': { uz: 'Parollar mos kelmadi', ru: 'Пароли не совпадают', en: 'Passwords do not match' },
  'login.register_as': { uz: "Ro'yxatdan o'ting", ru: 'Зарегистрируйтесь', en: 'Register' },
  'login.or': { uz: 'yoki', ru: 'или', en: 'or' },
  'login.scan_register': { uz: "Face ID bilan ro'yxatdan o'tish", ru: "Регистрация через Face ID", en: 'Register with Face ID' },
  'login.waiting': { uz: 'Kirish...', ru: 'Вход...', en: 'Signing in...' },

  // ── REAL VAQT NATIJALAR ──
  'results.my_results': { uz: 'Mening natijalarim', ru: 'Мои результаты', en: 'My Results' },
  'results.refresh': { uz: 'Yangilash', ru: 'Обновить', en: 'Refresh' },
  'results.total': { uz: 'Jami sinovlar', ru: 'Всего испытаний', en: 'Total exams' },
  'results.tests': { uz: 'Testlar', ru: 'Тесты', en: 'Tests' },
  'results.cases': { uz: 'Kazuslar', ru: 'Казусы', en: 'Cases' },
  'results.avg': { uz: "O'rtacha natija", ru: 'Средний результат', en: 'Average result' },
  'results.all': { uz: 'Barchasi', ru: 'Все', en: 'All' },
  'results.no_results': { uz: 'Hali natija yo\'q', ru: 'Пока нет результатов', en: 'No results yet' },
  'results.no_results_desc': { uz: 'Test yoki kazus yechganingizdan keyin bu yerda ko\'rinadi', ru: 'После решения теста или казуса это появится здесь', en: 'After solving a test or case it will appear here' },
  'results.correct': { uz: "To'g'ri", ru: 'Правильно', en: 'Correct' },
  'results.wrong': { uz: 'Xato', ru: 'Неверно', en: 'Wrong' },
  'results.unanswered': { uz: 'Javobsiz', ru: 'Без ответа', en: 'Unanswered' },
  'results.time_spent': { uz: 'Sarflangan vaqt', ru: 'Затраченное время', en: 'Time spent' },
  'results.analysis': { uz: 'Savollar tahlili', ru: 'Анализ вопросов', en: 'Questions analysis' },
  'results.ai_analysis': { uz: 'AI tahlil', ru: 'ИИ анализ', en: 'AI analysis' },
  'results.your_answer': { uz: 'Javobingiz', ru: 'Ваш ответ', en: 'Your answer' },
  'results.your_answer_label': { uz: 'Sizning javobingiz:', ru: 'Ваш ответ:', en: 'Your answer:' },
  'results.correct_answer': { uz: "To'g'ri javob:", ru: 'Правильный ответ:', en: 'Correct answer:' },
  'results.monitor': { uz: 'Kod bilan kuzatish', ru: 'Мониторинг по коду', en: 'Monitor by code' },
  'results.enter_code': { uz: '5 xonali kod kiriting', ru: 'Введите 5-значный код', en: 'Enter 5-digit code' },
  'results.start_monitoring': { uz: 'Kuzatishni boshlash', ru: 'Начать мониторинг', en: 'Start monitoring' },
  'results.detecting': { uz: 'Aniqlanmoqda...', ru: 'Определение...', en: 'Detecting...' },
  'results.stop': { uz: "To'xtatish", ru: 'Остановить', en: 'Stop' },
  'results.answers': { uz: 'javob', ru: 'ответов', en: 'answers' },
  'results.no_answers': { uz: 'Hali javob yo\'q...', ru: 'Пока нет ответов...', en: 'No answers yet...' },
  'results.loading': { uz: 'Natijalar yuklanmoqda...', ru: 'Загрузка результатов...', en: 'Loading results...' },
  'results.rating': { uz: 'Reyting va Baholash', ru: 'Рейтинг и Оценивание', en: 'Rating & Evaluation' },
  'results.monitor_desc': { uz: 'Test/kazus natijalarini kuzating va baholang', ru: 'Отслеживайте и оценивайте результаты теста/казуса', en: 'Monitor and evaluate test/case results' },
  'results.by_code': { uz: 'Kod bilan', ru: 'По коду', en: 'By code' },
  'results.my_tests': { uz: 'Mening testlarim', ru: 'Мои тесты', en: 'My Tests' },
  'results.my_cases': { uz: 'Mening kazuslarim', ru: 'Мои казусы', en: 'My Cases' },
  'results.back_to_tests': { uz: 'Testlarga qaytish', ru: 'Вернуться к тестам', en: 'Back to tests' },
  'results.back_to_cases': { uz: 'Kazuslarga qaytish', ru: 'Вернуться к казусам', en: 'Back to cases' },
  'results.participants': { uz: 'Ishtirokchilar', ru: 'Участники', en: 'Participants' },
  'results.passed': { uz: "O'tdi (60%+)", ru: 'Прошли (60%+)', en: 'Passed (60%+)' },
  'results.below': { uz: 'Past (<50%)', ru: 'Низкий (<50%)', en: 'Below (<50%)' },
  'results.excellent': { uz: "A'lo (85%+)", ru: 'Отлично (85%+)', en: 'Excellent (85%+)' },
  'results.avg_score': { uz: "O'rtacha", ru: 'Среднее', en: 'Average' },
  'results.total_answers': { uz: 'Jami', ru: 'Всего', en: 'Total' },
  'results.save': { uz: "O'zgarishlarni saqlash", ru: 'Сохранить изменения', en: 'Save Changes' },
  'results.saving': { uz: 'Saqlanmoqda...', ru: 'Сохранение...', en: 'Saving...' },
  'results.grade_edit': { uz: 'Baho tahrirlash', ru: 'Редактировать оценку', en: 'Edit Grade' },
  'results.comment': { uz: 'Ustoz izohi', ru: 'Комментарий преподавателя', en: 'Teacher comment' },
  'results.comment_placeholder': { uz: 'Izoh yozing...', ru: 'Напишите комментарий...', en: 'Write a comment...' },
  'results.comment_required': { uz: 'Izoh majburiy', ru: 'Комментарий обязателен', en: 'Comment is required' },
  'results.ball_range': { uz: 'Ball (0-30):', ru: 'Балл (0-30):', en: 'Score (0-30):' },
  'results.situation': { uz: 'Vaziyat:', ru: 'Ситуация:', en: 'Situation:' },
  'results.correct_ans': { uz: "To'g'ri javob:", ru: 'Правильный ответ:', en: 'Correct answer:' },
  'results.student_ans': { uz: "O'quvchi javobi:", ru: 'Ответ учащегося:', en: "Student's answer:" },
  'results.ai_conclusion': { uz: 'AI xulosasi:', ru: 'Заключение ИИ:', en: 'AI Conclusion:' },
  'results.no_answer': { uz: 'Javob berilmagan', ru: 'Ответ не дан', en: 'No answer given' },
  'results.no_test_created': { uz: 'Hali test yaratilmagan', ru: 'Тесты ещё не созданы', en: 'No tests created yet' },
  'results.no_case_created': { uz: 'Hali kazus yaratilmagan', ru: 'Казусы ещё не созданы', en: 'No cases created yet' },
  'results.status_active': { uz: '● Faol', ru: '● Активен', en: '● Active' },
  'results.status_stopped': { uz: "○ To'xtatilgan", ru: '○ Остановлен', en: '○ Stopped' },
  'results.no_answers_yet': { uz: 'Hali javob yo\'q', ru: 'Пока нет ответов', en: 'No answers yet' },
  'results.avg_pct': { uz: "O'rtacha %", ru: 'Среднее %', en: 'Average %' },
  'results.avg_score_short': { uz: "O'rtacha ball", ru: 'Средний балл', en: 'Avg score' },

  // ── BOSH SAHIFA (REYTING) ──
  'home.loading': { uz: 'Reyting yuklanmoqda...', ru: 'Загрузка рейтинга...', en: 'Loading rating...' },
  'home.rating_title': { uz: 'Bilimlar Reytingi', ru: 'Рейтинг знаний', en: 'Knowledge Rating' },
  'home.total_students': { uz: "Jami o'quvchilar", ru: 'Всего учащихся', en: 'Total students' },
  'home.total_tests': { uz: 'Jami testlar', ru: 'Всего тестов', en: 'Total tests' },
  'home.top_score': { uz: 'Eng yuqori ball', ru: 'Высший балл', en: 'Top score' },
  'home.students_rating': { uz: "O'quvchilar Reytingi", ru: 'Рейтинг учащихся', en: 'Students Rating' },
  'home.no_results': { uz: 'Hali natijalar yo\'q', ru: 'Пока нет результатов', en: 'No results yet' },
  'home.no_results_desc': { uz: 'Test yechish boshlanganda reyting paydo bo\'ladi', ru: 'Рейтинг появится, когда начнут решать тесты', en: 'Rating will appear when tests are started' },
  'home.place_1': { uz: "🥇 1-o'rin", ru: '🥇 1-е место', en: '🥇 1st place' },
  'home.place_2': { uz: "🥈 2-o'rin", ru: '🥈 2-е место', en: '🥈 2nd place' },
  'home.place_3': { uz: "🥉 3-o'rin", ru: '🥉 3-е место', en: '🥉 3rd place' },
  'home.total_score': { uz: 'Umumiy ball', ru: 'Общий балл', en: 'Total score' },
  'home.avg_label': { uz: "O'rtacha", ru: 'Среднее', en: 'Average' },
  'home.course': { uz: 'kurs', ru: 'курс', en: 'course' },
  'home.group': { uz: 'guruh', ru: 'группа', en: 'group' },
  'home.test_count': { uz: 'ta test', ru: 'тестов', en: 'tests' },
  'home.how_calc': { uz: 'Reyting qanday hisoblanadi?', ru: 'Как рассчитывается рейтинг?', en: 'How is the rating calculated?' },
  'home.how_calc_desc': { uz: "Reytingda o'quvchilarning barcha testlarda to'plagan umumiy ballari ko'rsatiladi. Eng ko'p ball to'plagan o'quvchilar TOP-3 ga kiradi! 🏆", ru: 'В рейтинге отображаются общие баллы учащихся по всем тестам. Учащиеся с наибольшим баллом входят в ТОП-3! 🏆', en: "The rating shows students' total scores across all tests. Students with the highest scores enter the TOP-3! 🏆" },

  // ── COMMON ──
  'common.loading': { uz: 'Yuklanmoqda...', ru: 'Загрузка...', en: 'Loading...' },
  'common.error': { uz: 'Xato', ru: 'Ошибка', en: 'Error' },
  'common.success': { uz: 'Muvaffaqiyatli', ru: 'Успешно', en: 'Success' },
  'common.cancel': { uz: 'Bekor qilish', ru: 'Отмена', en: 'Cancel' },
  'common.save': { uz: 'Saqlash', ru: 'Сохранить', en: 'Save' },
  'common.delete': { uz: "O'chirish", ru: 'Удалить', en: 'Delete' },
  'common.edit': { uz: 'Tahrirlash', ru: 'Редактировать', en: 'Edit' },
  'common.back': { uz: 'Orqaga', ru: 'Назад', en: 'Back' },
  'common.close': { uz: 'Yopish', ru: 'Закрыть', en: 'Close' },
  'common.search': { uz: 'Qidirish', ru: 'Поиск', en: 'Search' },
  'common.refresh': { uz: 'Yangilash', ru: 'Обновить', en: 'Refresh' },
  'common.create': { uz: 'Yaratish', ru: 'Создать', en: 'Create' },
  'common.upload': { uz: 'Yuklash', ru: 'Загрузить', en: 'Upload' },
  'common.welcome': { uz: 'Xush kelibsiz!', ru: 'Добро пожаловать!', en: 'Welcome!' },
  'common.or': { uz: 'yoki', ru: 'или', en: 'or' },
  'common.yes': { uz: 'Ha', ru: 'Да', en: 'Yes' },
  'common.no': { uz: "Yo'q", ru: 'Нет', en: 'No' },
  'common.min': { uz: 'daqiqa', ru: 'мин', en: 'min' },
  'common.sec': { uz: 'soniya', ru: 'сек', en: 'sec' },
  'common.score': { uz: 'ball', ru: 'балл', en: 'score' },
  'common.percent': { uz: 'foiz', ru: 'процент', en: 'percent' },
  'common.total': { uz: 'Jami', ru: 'Всего', en: 'Total' },
  'common.active': { uz: 'Faol', ru: 'Активен', en: 'Active' },
  'common.inactive': { uz: 'Nofaol', ru: 'Неактивен', en: 'Inactive' },
  'common.status': { uz: 'Holat', ru: 'Статус', en: 'Status' },
  'common.date': { uz: 'Sana', ru: 'Дата', en: 'Date' },
  'common.name': { uz: 'Ism', ru: 'Имя', en: 'Name' },
  'common.surname': { uz: 'Familiya', ru: 'Фамилия', en: 'Surname' },
  'common.group': { uz: 'Guruh', ru: 'Группа', en: 'Group' },
  'common.course': { uz: 'Kurs', ru: 'Курс', en: 'Course' },
};

const LangContext = createContext<LangContextType>({
  lang: 'uz',
  setLang: () => {},
  t: (k) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('site_lang') as Lang) || 'uz';
  });

  const setLang = (l: Lang) => {
    localStorage.setItem('site_lang', l);
    setLangState(l);
  };

  const t = (key: string): string => {
    return translations[key]?.[lang] ?? translations[key]?.uz ?? key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
