/*
# Create telegram_login_sessions, bot_sessions, and parol_reset_kodlar tables

## Purpose
These three tables are required for the Telegram login flow and ustoz (teacher) registration bot.
They were missing from the current database, causing "Could not find the table" errors.

## New Tables

### 1. telegram_login_sessions
Stores login session tokens for the Telegram-based o'quvchi (student) login flow.
- session_token: unique hex token generated by the frontend
- status: pending → confirmed → used (lifecycle)
- expires_at: 5-minute expiry from creation
- telegram_id, telegram_ism, telegram_familiya, telegram_username: filled when bot confirms
- talaba_id, login_id, ism, familiya, guruh, kurs: student info for frontend login

### 2. bot_sessions
Stores per-chat state for both Telegram bots (login bot + ustoz registration bot).
- chat_id: Telegram chat ID (primary key)
- telegram_id: Telegram user ID
- state: state machine value (e.g. login_waiting_phone, ustoz_waiting_phone, etc.)
- phone, ism, familiya, login_id: intermediate data collected during the flow
- updated_at: last update timestamp

### 3. parol_reset_kodlar
Stores OTP codes for ustoz password reset flow.
- login_id: phone number identifier
- kod: 5-digit OTP code
- faol: boolean (active/inactive)
- expires_at: 10-minute expiry

## Security
- RLS enabled on all tables.
- Policies allow anon + authenticated CRUD (these tables are used by the anon-key frontend
  and by edge functions using the service role key which bypasses RLS).
*/

-- ── telegram_login_sessions ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS telegram_login_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_token text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending',
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '5 minutes'),
  telegram_id bigint,
  telegram_ism text,
  telegram_familiya text,
  telegram_username text,
  talaba_id uuid,
  login_id text,
  ism text,
  familiya text,
  guruh text,
  kurs text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE telegram_login_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_login_sessions" ON telegram_login_sessions;
CREATE POLICY "anon_select_login_sessions" ON telegram_login_sessions
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_login_sessions" ON telegram_login_sessions;
CREATE POLICY "anon_insert_login_sessions" ON telegram_login_sessions
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_login_sessions" ON telegram_login_sessions;
CREATE POLICY "anon_update_login_sessions" ON telegram_login_sessions
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_login_sessions" ON telegram_login_sessions;
CREATE POLICY "anon_delete_login_sessions" ON telegram_login_sessions
  FOR DELETE TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_tls_session_token ON telegram_login_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_tls_status ON telegram_login_sessions(status);

-- ── bot_sessions ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bot_sessions (
  chat_id bigint PRIMARY KEY,
  telegram_id bigint,
  state text DEFAULT '',
  phone text,
  ism text,
  familiya text,
  login_id text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE bot_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_bot_sessions" ON bot_sessions;
CREATE POLICY "anon_select_bot_sessions" ON bot_sessions
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_bot_sessions" ON bot_sessions;
CREATE POLICY "anon_insert_bot_sessions" ON bot_sessions
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_bot_sessions" ON bot_sessions;
CREATE POLICY "anon_update_bot_sessions" ON bot_sessions
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_bot_sessions" ON bot_sessions;
CREATE POLICY "anon_delete_bot_sessions" ON bot_sessions
  FOR DELETE TO anon, authenticated USING (true);

-- ── parol_reset_kodlar ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS parol_reset_kodlar (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  login_id text NOT NULL,
  kod text NOT NULL,
  faol boolean NOT NULL DEFAULT true,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '10 minutes'),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE parol_reset_kodlar ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_reset_kodlar" ON parol_reset_kodlar;
CREATE POLICY "anon_select_reset_kodlar" ON parol_reset_kodlar
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_reset_kodlar" ON parol_reset_kodlar;
CREATE POLICY "anon_insert_reset_kodlar" ON parol_reset_kodlar
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_reset_kodlar" ON parol_reset_kodlar;
CREATE POLICY "anon_update_reset_kodlar" ON parol_reset_kodlar
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_reset_kodlar" ON parol_reset_kodlar;
CREATE POLICY "anon_delete_reset_kodlar" ON parol_reset_kodlar
  FOR DELETE TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_prk_login_id ON parol_reset_kodlar(login_id);
