/*
# Fix case source uploads for the app's custom teacher login

1. Purpose
- The frontend uses the app's custom teacher session rather than a Supabase Auth session.
- The previous upload policy allowed only the `authenticated` Supabase role, so valid teachers received a generic upload failure.

2. Storage changes
- Allow the public client role to INSERT objects only into the private `case-sources` bucket.
- Keep browser SELECT and DELETE blocked; the stored files remain private and are accessed by server-side processing.
- Restrict the bucket to PDF and DOCX files with a 40 MB maximum size.

3. Security notes
- The bucket remains private.
- The upload path is still generated by the application as `{teacher_id}/{uuid}/{filename}`.
- No permissions are changed for any other bucket.
*/

UPDATE storage.buckets
SET
  file_size_limit = 41943040,
  allowed_mime_types = ARRAY[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
WHERE id = 'case-sources';

DROP POLICY IF EXISTS "case_sources_upload_custom_auth" ON storage.objects;
CREATE POLICY "case_sources_upload_custom_auth"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (
  bucket_id = 'case-sources'
  AND (storage.foldername(name))[1] IS NOT NULL
  AND (storage.foldername(name))[2] IS NOT NULL
  AND lower(storage.extension(name)) IN ('pdf', 'docx')
);
